#!/bin/bash

echo "=========================================="
echo "   Seraphin Premium GUI - Fish It Script"
echo "=========================================="
echo ""
echo "Script file: SeraphinGUI.lua"
echo "Lines: $(wc -l < SeraphinGUI.lua)"
echo ""
echo "=========================================="
echo "   HOW TO USE"
echo "=========================================="
echo ""
echo "1. Copy the content of SeraphinGUI.lua"
echo "2. Open your Roblox executor (Synapse X, KRNL, etc.)"
echo "3. Paste the script and execute"
echo ""
echo "=========================================="
echo "   FEATURES"
echo "=========================================="
echo ""
echo "- Dark transparent GUI (Seraphin Premium style)"
echo "- Sidebar navigation: Info, Exclusive, Main, Menu, Trading, Quest"
echo "- Manual delay input (TextBox instead of sliders)"
echo "- Toggle switches for features"
echo "- Logo only visible when minimized"
echo "- No spinning animation on close"
echo ""
echo "=========================================="
echo "   SCRIPT PREVIEW (first 50 lines)"
echo "=========================================="
echo ""
head -50 SeraphinGUI.lua
echo ""
echo "... (script continues)"
echo ""
echo "=========================================="
echo "Script ready to use!"
